version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: quantiva_redis
    # ports removed to secure redis from external access
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: quantiva_rabbitmq
    ports:
      - "15672:15672" # Management UI exposed for you to monitor queues
    # 5672 (AMQP port) removed to secure against external workers
    restart: unless-stopped

  service1:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_1
      dockerfile: dockerfile
    container_name: quantiva_s1
    ports:
      - "80:3000" # ONLY the API Gateway is exposed to the internet on standard HTTP port 80
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  service2:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_2
      dockerfile: Dockerfile
    container_name: quantiva_s2
    # ports removed to secure the worker from external access
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  service3:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_3
      dockerfile: Dockerfile
    container_name: quantiva_s3
    # ports removed to secure the worker from external access
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  service4:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_4
      dockerfile: Dockerfile
    container_name: quantiva_s4
    # ports removed to secure the worker from external access
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped
