version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: quantiva_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: quantiva_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    restart: unless-stopped

  service1:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_1
      dockerfile: dockerfile # lowercase 'd' as it is in the directory
    container_name: quantiva_s1
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  service2:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_2
      dockerfile: Dockerfile
    container_name: quantiva_s2
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  service3:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_3
      dockerfile: Dockerfile
    container_name: quantiva_s3
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped

  service4:
    build: 
      context: ./QUANTIVA_3.0_SERVICE_4
      dockerfile: Dockerfile
    container_name: quantiva_s4
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - REDIS_KEY=redis://redis:6379
      - RABITMQ_KEY=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped
